### ISSUE TITLE
select date_format error

### ISSUE THREAD

**Issue by jngz-es** [opendistro-for-elasticsearch/sql-jdbc#14]
The query "SELECT date_format(mydate, 'yyyy-mm-dd') AS date, COUNT(*) AS count, SUM('aaa') AS sum FROM table GROUP BY date_format(mydate, 'yyyy-mm-dd')" got error w/ JDBC, but works w/o JDBC.

The error, com.amazon.opendistroforelasticsearch.jdbc.protocol.exceptions.InternalServerErrorException.

**Comment by galkk** [comment]
After referenced PR the query doesn't fails anymore

```
POST _opendistro/_sql?format=jdbc
{
  "query": "SELECT date_format(utc_time, 'dd-MM-YYYY'), count(*)  from kibana_sample_data_logs group by date_format(utc_time, 'dd-MM-YYYY')"
}
```
but has suspicious column in the result.

**Comment by galkk** [comment]
This is SQL plugin issue, not JDBC. It will be worket here: 
[sql-111](https://github.com/opendistro-for-elasticsearch/sql/issues/111)
