### ISSUE TITLE
Tableau - SQL JDBC support

### ISSUE THREAD

**Issue by CarlMeadows** [opendistro-for-elasticsearch/sql-jdbc#2]
Add support for Tableau to the SQL JDBC driver.

**Comment by epical-mi** [comment]
Just tested the JDBC driver against Tableau. During its connection testing process, Tableau seems to try to create a temporary table to test some SQL capabilities of the JDBC driver/DB and then drops the table. I can see these error messages from ES logs. As these features are not supported, the connection fails.

```
java.sql.SQLFeatureNotSupportedException: Unsupported query: CREATE LOCAL TEMPORARY TABLE XT____AB_________D__C_C______B___F_B_BC___1_Connect_CheckCreateTempTableCap ( 	COL INTEGER    	) ON COMMIT PRESERVE ROWS
java.sql.SQLFeatureNotSupportedException: Unsupported query: DROP TABLE XT____AB_________D__C_C______B___F_B_BC___1_Connect_CheckCreateTempTableCap
```

**Comment by luhhujbb** [comment]
We have the same issue when we try the presto jdbc driver. Maybe a read-only option for jdbc could solve this.

**Comment by rupal-bq** [comment]
You can add `<customization name='CAP_CREATE_TEMP_TABLES' value='no'/>` in .tdc file to avoid creating temporary tables.
For more information check [Connecting Tableau with Open Distro for Elasticsearch](https://github.com/opendistro-for-elasticsearch/sql-jdbc/blob/master/docs/tableau.md).
