### ISSUE TITLE
using jdbc, some sql functions seem not work normally

### ISSUE THREAD

**Issue by jianhong2014** [opendistro-for-elasticsearch/sql-jdbc#23]
e.g. date_format works normally using postman, but doesn't work in java env

**Comment by dai-chen** [comment]
> e.g. date_format works normally using postman, but doesn't work in java env

Hey @jianhong2014 , could you provide more information so we can duplicate the issue? Such as your env, data and query etc.

**Comment by jianhong2014** [comment]
![image](https://user-images.githubusercontent.com/6869413/63078228-6fd3c200-bf6d-11e9-8ff4-5431320a086c.png)

**Comment by jianhong2014** [comment]
![image](https://user-images.githubusercontent.com/6869413/63078292-a1e52400-bf6d-11e9-98b3-8d2e0bb93a96.png)

**Comment by jianhong2014** [comment]
![image](https://user-images.githubusercontent.com/6869413/63078438-0dc78c80-bf6e-11e9-9b6f-dfd39c092073.png)

**Comment by dai-chen** [comment]
Thanks for the update! Will look into the issue and request more information if needed.

**Comment by jianhong2014** [comment]
any update? if possible，we can talk directly

**Comment by galkk** [comment]
Hello @jianhong2014 

Thanks for the feedback. Could you clarify couple of quiestions

1. Which version of the driver you are using?
2. Could you show the ouput of your query from Kibana, using this as an example

```
GET /_opendistro/_sql?format=jdbc
{
  "query": """
  SELECT date_format(utc_time, 'Y-MM-dd') x, count(*) 
  FROM kibana_sample_data_logs
  WHERE host='www.elastic.co'
  GROUP BY date_format(utc_time, 'Y-MM-dd')
  """
}

GET /_opendistro/_sql?format=jdbc
{
  "query": """
  SELECT date_format(utc_time, 'Y-MM-dd') x, count(*) 
  FROM kibana_sample_data_logs
  WHERE host='www.elastic.co'
  GROUP BY x
  """
}

```
