### ISSUE TITLE
Can not parse 2019-10-01 01:24:16.191Z as a Timestamp

### ISSUE THREAD

**Issue by k-sea** [opendistro-for-elasticsearch/sql-jdbc#25]
Hi, I'm running into issues with timestamps in our elasticSearch, the JDBC driver is returning the following.

Can not parse 2019-10-01 01:24:16.191Z as a Timestamp

this is when I include one of our timestamp fields in the select columns.

I'm looking at your jdbc/types/TimestampType.java routine and I think it's off by 1 char, thinking this should be looking at Z as the 24th char not 23rd but it seems to work with removal of T so I'm confused.

Any thoughts on what might be happening here?

// Make some effort to understand ISO format
            if (value.length() > 11 && value.charAt(10) == 'T') {
                value = value.replace('T', ' ');
            }
            // Timestamp.valueOf() does not like timezone information
            if (value.length() > 23) {
                if (value.length() == 24 && value.charAt(23) == 'Z') {
                    value = value.substring(0, 23);
                }
                else if (value.charAt(23) == '+' || value.charAt(23) == '-') {
                    // 'calendar' parameter takes precedence
                    if (calendar == null) {
                        calendar = Calendar.getInstance(TimeZone.getTimeZone("GMT" + value.substring(23)));
                    }
                    value = value.substring(0, 23);
                }
            }

Thank you for your work on this project, this is going to come in really handy.

**Comment by penghuo** [comment]
@k-sea Thanks for reporting the issue.
I am trying to understand your issue. I add the UT in TimestampTypeTests and it passed.
```
    @ParameterizedTest
    @CsvSource(value = {
            "2019-10-01 01:24:16.191Z, 1569893056191"
    })
    void issue25(String stringValue, long longValue) {
        Timestamp timestamp = Assertions.assertDoesNotThrow(
                () -> TimestampType.INSTANCE.fromValue(stringValue, null));
        assertEquals(longValue, timestamp.getTime());
    }
```

**Comment by dai-chen** [comment]
@k-sea Please let us know if you still have the issue. Or we will be closing it later.
