### ISSUE TITLE
Select using multi indexes

### ISSUE THREAD

**Issue by snuids** [opendistro-for-elasticsearch/sql-jdbc#3]
Hi,

I am using the driver with jasper report and it works like a charm. However, I cannot make queries such as:

select * from logtstash*

This query is working using the open distro plugin via the Rest API.

Am I missing something ?

Thanks,

**Comment by dai-chen** [comment]
Hi, this is related to https://github.com/opendistro-for-elasticsearch/sql/issues/9. We've root caused and will be fixing it.

**Comment by snuids** [comment]
Great Thx !

**Comment by vinjosh** [comment]
Duplicate of https://github.com/opendistro-for-elasticsearch/sql/issues/9

**Comment by dai-chen** [comment]
Fixed and merged.
