### ISSUE TITLE
can this support Elastic elasticsearch?

### ISSUE THREAD

**Issue by ltylty** [opendistro-for-elasticsearch/sql-jdbc#34]
can this support Elastic elasticsearch?

**Comment by dai-chen** [comment]
Hi @ltylty, yes, it should work. You need to install our SQL plugin to your Elasticsearch. You can try it out and let me know if any issue.

**Comment by ltylty** [comment]
Thank you。 I will try it。

**Comment by dai-chen** [comment]
> Thank you。 I will try it。

You're welcome! This may be helpful: https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#sql
