### ISSUE TITLE
Need help in identifying elasticsearch schema name while testing with the tableau desktop

### ISSUE THREAD

**Issue by ravipalaparthi** [opendistro-for-elasticsearch/sql-jdbc#48]
Hello team,

I followed the instructions that are available in https://github.com/opendistro-for-elasticsearch/sql-jdbc/blob/master/docs/tableau.md

I am able to connect but after selecting the database "elasticsearch". It is asking me to select or enter the schema name which I could not understand. Can you please let me know what should be the schema name for ES indexes. 

![image](https://user-images.githubusercontent.com/33325116/72477787-56ee6780-37be-11ea-9fb4-7362d8516f62.png)

Thanks In advance. 

Regards,
Ravi

**Comment by dai-chen** [comment]
@abbashus have you met this problem before?

**Comment by abbashus** [comment]
I have not encountered this issue before. This is the first time I am seeing this option to select Database and Schema; it should automatically list out all the tables.


@ravipalaparthi What Tableau Desktop version you are using? What is the ES version and OpenDistro SQL-JDBC version are you using?

**Comment by ravipalaparthi** [comment]
I am using the following versions:

- Tableau Desktop version 2018.3.13 (Windows 64 bit version)
- ES 6.6.2
- OpenDistro SQL JDBC opendistro-sql-jdbc-1.3.0.0.jar

**Comment by abbashus** [comment]
I used the following config

- Tableau Desktop version 2019.3.2 (MacOS version)
-  ES 7.4.2
- OpenDistro SQL JDBC opendistro-sql-jdbc-1.3.0.0.jar (downloaded from [here](https://opendistro.github.io/for-elasticsearch/downloads.html))

It automagically lists out all the tables for me.

<img width="752" alt="Screen Shot 2020-01-16 at 10 21 17 AM" src="https://user-images.githubusercontent.com/46726078/72552159-1f79cc80-384b-11ea-9499-1d1791c39699.png">

This possibly looks like Tableau issue. Could you try changing the Tableau Version and see if it works, may be upgrade ES as well? Can you also share the Tableau Desktop logs with error/stack trace - you can find them in `C:\Documents and Settings\user\My Documents\My Tableau Repository\Logs\jdbcserver.log`  for Windows.

**Comment by ravipalaparthi** [comment]
@abbashus trying with the suggested versions. will update you shortly.

**Comment by ravipalaparthi** [comment]
@abbashus As you said, installed 

- Tableau Desktop version 2019.3.2 (Windows version)
- ES 7.4.2
- OpenDistro SQL JDBC opendistro-sql-jdbc-1.3.0.0.jar (downloaded from the suggested link)

This time it's failing to connect. Please find the jdbcserver.log
[jdbcserver.log](https://github.com/opendistro-for-elasticsearch/sql-jdbc/files/4073649/jdbcserver.log)

For reference, Attached elasticsearch.tdc
[elasticsearch.tdc.txt](https://github.com/opendistro-for-elasticsearch/sql-jdbc/files/4073663/elasticsearch.tdc.txt)  [Note: To attach this file, i renamed it to elasticsearch.tdc.txt"

**Comment by abbashus** [comment]
Hi @ravipalaparthi , if you have access to `elasticsearch.log` , you can see what SQL queries are being fired from Tableau. Can you share that as well? Need to reproduce from our end.

Can you also provide Index mappings for the indices in your cluster.

```
curl -XGET "http://localhost:9200/_mappings"
```

**Comment by ravipalaparthi** [comment]
Hi @abbashus Sorry for the delayed response. I just created a simple index with the below mapping and data

![image](https://user-images.githubusercontent.com/33325116/72754874-0056a400-3b97-11ea-9d61-acc399d25ae2.png)

**PUT /my-index**
{
  "mappings": {
    "properties": {
      "age":    { "type": "integer" },  
      "email":  { "type": "keyword"  }, 
      "name":   { "type": "text"  }     
    }
  }
}

**PUT /my-index/_doc/1**
{
  "name": "John Doe",
  "age": 10,
  "email":"ravi@ravi.com"
}

**PUT /my-index/_doc/2**
{
  "name": "Doe 2",
  "age": 10,
  "email":"ravi@ravi.com"
}

**PUT /my-index/_doc/3**
{
  "name": "John 1",
  "age": 10,
  "email":"ravi@ravi.com"
}


I Could not find the queries that were fired from Tableau. Attached are my ES logs 
[ES logs.zip](https://github.com/opendistro-for-elasticsearch/sql-jdbc/files/4087589/ES.logs.zip)
Can you please review them once and let me know if we are missing something. 

Also, In Tableau Desktop 2019.3, I am not able to signin when I place the **elasticsearch.tdc** under **C:\Users\<<USER_ACCOUNT>>\Documents\My Tableau Repository\Datasources** but I am able to sign in, get the below view if I place the same file under **C:\Program Files\Tableau\Tableau 2019.3\defaults\Datasources**. 

![image](https://user-images.githubusercontent.com/33325116/72752927-84a62880-3b91-11ea-86d8-ee293e6fe74f.png)

**Comment by ravipalaparthi** [comment]
Hello @abbashus it will be great if you can help us in addressing this issue.

**Comment by abbashus** [comment]
@ravipalaparthi  I checked your `elasticsearch.log` , it does not have `opendistro_sql` plugin installed.  The `opendistro-sql-jdbc` driver is compatible with `opendistro_sql` plugin . Instead it has got other proprietary plugins starting with `x-`.   You can either build it [locally](https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/developing.rst) or get it pre-packaged with dockerized OpenDisrto Elasticsearch version [here](https://opendistro.github.io/for-elasticsearch/downloads.html)



You can check `opendistro_sql` is installed by checking either 
```
GET _cat/plugins?pretty
```

OR 

hitting the `_opendistro/_sql` endpoint
```
curl -XPOST "http://localhost:9200/_opendistro/_sql/?" -H 'Content-Type: application/json' -d'{  "query" : "  SELECT * FROM my_index"}'
```

**Comment by ravipalaparthi** [comment]
Hi @abbashus As suggested I have downloaded [odfe-1.3.0.zip](https://opendistro.github.io/for-elasticsearch-docs/docs/install/windows/), disabled HTPPS with **opendistro_security.ssl.http.enabled:false**, created "my-index" with mapping and sample data by login with **admin/admin** and tried to access the tables from the Tableau desktop **but it's still asking me to select the schema.** 

More configuration details: 

1. OpenDistro plugins
     
![image](https://user-images.githubusercontent.com/33325116/72918028-f194fc00-3d12-11ea-9d9f-46cf79b5b780.png)

2. Access "my-index" data using SQL support
![image](https://user-images.githubusercontent.com/33325116/72918138-2739e500-3d13-11ea-900d-aa7340b482f6.png)

3. Tableau Desktop - Connect to ES using Other Databases (JDBC)

![image](https://user-images.githubusercontent.com/33325116/72918238-551f2980-3d13-11ea-8093-ba3e45857759.png)

4. Tableau Desktop - After successful login; I was able to select the database "elasticsearch" and it's forcing me to select the schema name
![image](https://user-images.githubusercontent.com/33325116/72918841-5ac93f00-3d14-11ea-8130-d6e851e5dbdd.png)


4. Placed OpenDistro SQL JDBC driver at 
![image](https://user-images.githubusercontent.com/33325116/72918358-8566c800-3d13-11ea-960f-247921bf4af9.png)

5. Placed elasticsearch.tdc at 
![image](https://user-images.githubusercontent.com/33325116/72918424-a29b9680-3d13-11ea-9c66-9127d16acfcf.png)

6. jdbcserver.log for reference
[jdbcserver.log](https://github.com/opendistro-for-elasticsearch/sql-jdbc/files/4098855/jdbcserver.log)

7. elastic search log for reference
[elasticsearch.log](https://github.com/opendistro-for-elasticsearch/sql-jdbc/files/4098875/elasticsearch.log)


Am I missing something? Please suggest.

I appreciate your help.

**Comment by ravipalaparthi** [comment]
Hi @abbashus @dai-chen and OpenDistroTeam,  we are stuck with the above issue and looking for some inputs which can help us to resolve the schema selection.

**Comment by abbashus** [comment]
Hi @ravipalaparthi, please PM me on my [public email ID](https://github.com/abbashus) to help you out offline. It's working correctly on our end. May be some Tableau version issue, or Windows issue.

**Comment by abbashus** [comment]
I see Tableau is firing below query resulting in connection error

```
CREATE TABLE `#Tableau___EAF_C_AE_A_B___E_A__F______C_DDBAEA__1_Connect_Chec` (
	`COL` INTEGER
	)
```
 which implies either`.tdc` file is not being picked up or is not configured properly.

**Comment by jordanw-bq** [comment]
Hi @ravipalaparthi,

https://github.com/opendistro-for-elasticsearch/sql-jdbc/issues/48#issuecomment-577302621
In this comment at step 6, I noticed that you placed the TDC file under `Documents\My Tableau Repository\Datasources\<version>`. Can you move the file up to the parent folder and see if that helps? (`Documents\My Tableau Repository\Datasources` instead)

**Comment by ravipalaparthi** [comment]
Hi @abbashus, @jordanw-bq 

As suggested, I moved the .tdc file back to C:\Users\<<USER>>\Documents\My Tableau Repository\Datasources and tried to access the ES from the Tableau desktop. This time, It did not through any errors (like CREATE TABLE .....) in ES log but after selecting the Database "elasticsearch" it's still looking schema details. 

![image](https://user-images.githubusercontent.com/33325116/73313759-177e3d00-41fa-11ea-80c8-80d1b41b6fb8.png)

**Comment by jordanw-bq** [comment]
@ravipalaparthi Can you share the contents of your TDC file with us, so that we can confirm that the correct customizations are being set?

**Comment by ghost** [comment]
Hi @ravipalaparthi,  I have noticed in one comment that you have saved customization file as “elasticsearch.tdc.txt”. Try renaming it to “elasticsearch.tdc”.

**Comment by ravipalaparthi** [comment]
@jordanw-bq  Please find the attached TDC file. 

[elasticsearch.zip](https://github.com/opendistro-for-elasticsearch/sql-jdbc/files/4140154/elasticsearch.zip)

@rupalmahajan yeah, I am using *.tdc only. To attach this file, I renamed it to elasticsearch.tdc.txt

**Comment by lyndonbauto** [comment]
@ravipalaparthi Could you please do the following:

1. Go to ( User )\Documents\My Tableau Repository\Logs (with Tableau closed)
2. Delete the existing logs
3. Open Tableau and connect with the JDBC driver to get to the point where the schema pops up
4. Open ( User )\Documents\My Tableau Repository\Logs\log.txt and post it here

We can review the log and look for issues there.

Thank you

**Comment by ravipalaparthi** [comment]
Hi @lyndonb-bq, I apologize for the late response. I came to the client's place, little busy with other stuff and could not find a chance to look at these updates. I will provide an update by the end of Monday.

**Comment by ravipalaparthi** [comment]
Hi @abbashus @dai-chen @jordanw-bq @rupalmahajan I just tried to connect the Opendistro ES from my tableau desktop and **surprisingly it's working!!!**  

> I did not make any changes

 

**Thanks for all your support and help !!!** 

**For future reference, I am just reposting my configuration details -** 
**_Other Databases (JDBC)_**
![image](https://user-images.githubusercontent.com/33325116/74473441-9c5f8c80-4e71-11ea-9f74-9cfa14da19a1.png)

**_Tableau Desktop with ES index details_** 
![image](https://user-images.githubusercontent.com/33325116/74470413-7be10380-4e6c-11ea-84cf-f1b817784827.png)

**_Tableau Desktop Version:_**
![image](https://user-images.githubusercontent.com/33325116/74470502-aa5ede80-4e6c-11ea-9d20-2be552a875ff.png)

**_TDC File Path:_**
![image](https://user-images.githubusercontent.com/33325116/74470622-e6923f00-4e6c-11ea-9159-6a1669282717.png)

**_TDC File:_**
[elasticsearch.zip](https://github.com/opendistro-for-elasticsearch/sql-jdbc/files/4200575/elasticsearch.zip)
**No references of tdc files in any of the version-specific folders.**

**_OpenDistro JDBC Driver path:_**
![image](https://user-images.githubusercontent.com/33325116/74470830-37a23300-4e6d-11ea-9208-54163f6562ae.png)

**_Opendistro ES Details:_**
![image](https://user-images.githubusercontent.com/33325116/74471443-3291b380-4e6e-11ea-846d-315c700df580.png)

**_ES Plugin Details_**
![image](https://user-images.githubusercontent.com/33325116/74471525-59e88080-4e6e-11ea-9199-e5a56bcd154b.png)

**_ES version details_**
![image](https://user-images.githubusercontent.com/33325116/74472919-bd73ad80-4e70-11ea-91b8-6dd577572d10.png)

**Comment by abbashus** [comment]
@ravipalaparthi  Glad it worked out! Though it **surprisingly worked**, but we would want to know the root cause. If you find one, keep us posted.

**Comment by ravipalaparthi** [comment]
sure @abbashus Let me look at the opportunities to replicate the issue in one of my co-worker's work stations.
