### ISSUE TITLE
Failed to read index from Dbeaver

### ISSUE THREAD

**Issue by sandeep-veerlapati** [opendistro-for-elasticsearch/sql-jdbc#57]
I am using a Dbeaver to access Elasticsearch service on AWS.  I am facing an error while trying to access an index having around 100 fields.  Though I am able to query the index from the editor, I can't see the schema in the data explorer.
Please find below image for more details about the error.
![image](https://user-images.githubusercontent.com/37291294/76325722-a6a86580-630d-11ea-8b51-daabdb82c31a.png)

**Comment by penghuo** [comment]
Thanks for reporting the issue.
Is it possible to share the index mapping to help debug the issue. 
My current guess is the type is missing from the [ElasticsearchType](https://github.com/opendistro-for-elasticsearch/sql-jdbc/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/jdbc/types/ElasticsearchType.java).

**Comment by Jayu8** [comment]
Attached the index mapping

**Comment by penghuo** [comment]
The issues in because the SQL plugin return the field without type info when the field in Elasticsearch mapping is object type. User are not required to set the field type to object explicitly, as this is the default value.

* The mapping in Elasticsearch index which use implicit Object type.
```
        "stats" : {
          ”type":"object",
          "properties" : {
            "100%" : {
              "type" : "float"
            },
            "25%" : {
              "type" : "float"
            },
            "50%" : {
              "type" : "float"
            },
            "75%" : {
              "type" : "float"
            },
            "count" : {
              "type" : "float"
            },
            "max" : {
              "type" : "float"
            },
            "mean" : {
              "type" : "float"
            },
            "min" : {
              "type" : "float"
            },
            "std" : {
              "type" : "float"
            }
          }
        },
```

Result of query `DESCRIBE TABLES LIKE kbs-datalake COLUMNS LIKE %`
```
    [
      "elasticsearch",
      null,
      "kbs-datalake",
      "stats",
      null,
      null,
      null,
      null,
      null,
      10,
      2,
      null,
      null,
      null,
      null,
      null,
      10,
      "",
      null,
      null,
      null,
      null,
      "NO",
      ""
    ],
```

**Comment by penghuo** [comment]
One workaround is add the "type":"object" for the field explicitly
