### ISSUE TITLE
Can not parse 2020-03-23T09:28:48+00:00 as a Timestamp

### ISSUE THREAD

**Issue by sunnyfun888** [opendistro-for-elasticsearch/sql-jdbc#60]
The format of Timestamp is different in our elasticSearch, which we got is like
2020-03-23T09:28:48+00:00

I changed the source code of jdbc/types/TimestampType.java
from

            // Timestamp.valueOf() does not like timezone information
            if (value.length() > 23) {
                if (value.length() == 24 && value.charAt(23) == 'Z') {
                    value = value.substring(0, 23);
                }
                else if (value.charAt(23) == '+' || value.charAt(23) == '-') {
                    // 'calendar' parameter takes precedence
                    if (calendar == null) {
                        calendar = Calendar.getInstance(TimeZone.getTimeZone("GMT" + value.substring(23)));
                    }
                    value = value.substring(0, 23);
                }
            }

to

            // Timestamp.valueOf() does not like timezone information
            if (value.length() > 23) {
                if (value.length() == 24 && value.charAt(23) == 'Z') {
                    value = value.substring(0, 23);
                } else {
					int delimiterIndex = value.length() - 6;
					if (value.charAt(delimiterIndex) == '+'
						  || value.charAt(delimiterIndex) == '-') {
					    // 'calendar' parameter takes precedence
					    if (calendar == null) {
					        calendar = Calendar.getInstance(
					        		TimeZone.getTimeZone("GMT" + value.substring(delimiterIndex)));
					    }
					    value = value.substring(0, delimiterIndex);
					}
				}
            }

It seems the compatibility is better.

**Comment by dai-chen** [comment]
@sunnyfun888 Thanks for reporting! Will look into the issue.

**Comment by anirudha** [comment]
please confirm if this works and re-open as necessary.
