### ISSUE TITLE
Re-Open Build from source to make compatible for Elasticsearch 7.6.2

### ISSUE THREAD

**Issue by fadjar340** [opendistro-for-elasticsearch/sql-jdbc#79]
Please reopen this issue if you have questions

_Originally posted by @anirudha in https://github.com/opendistro-for-elasticsearch/sql-jdbc/issues/78#issuecomment-626314190_

After build from source, I have the opendistro_sql-1.7.0.0-SNAPSHOT.jar, then I use it in dbeaver.
The problem is the same, bad request, since I saw in https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/, it should install the opendistro-sql-xxx.zip, when I following the URL, the result said that the plugins for 7.6.1.
How I can use it in 7.6.2? Please give a hint...

Regards,
Fadjar Tandabawana

**Comment by abbashus** [comment]
~~Change `elasticsearch.version` to `7.6.2` in `plugin-descriptor.properties` file. This file is being used by Elasticsearch to load the plugin, and complains if there is a mismatch between versions.~~

Please ignore, I thought it was meant for SQL plugin.

**Comment by abbashus** [comment]
~~**Option two**: Change `es_version` in `build.gradle` under project root and do a rebuild. This will generate a new jar build with ES 7.6.2 and also generate appropriate `plugin-descriptor.properties` file.~~

Please ignore, I thought it was meant for SQL plugin.

**Comment by penghuo** [comment]
You should build the plugin https://github.com/opendistro-for-elasticsearch/sql to make it compatible with Elasticsearch 7.6.2. [Here is the code.](https://github.com/opendistro-for-elasticsearch/sql/blob/master/build.gradle#L18) 
Because JDBC just use RESTful enpoint, there should be no change regarding to JDBC.

**Comment by fadjar340** [comment]
Oke, 

I'll try to build it...


Regards,
Fadjar Tandabawana
