### ISSUE TITLE
New Maven Endpoint for ODFE

### ISSUE THREAD

**Issue by gaiksaya** [opendistro-for-elasticsearch/sql-jdbc#83]
Hi,
The maven endpoint for ODFE has changed from https://oss.sonatype.org/service/local/staging/deploy/maven2 to https://aws.oss.sonatype.org/service/local/staging/deploy/maven2

The login credentials are the same as before. However, the user token has been updated. Infra team will updated the user token credentials (used in maven workflows). However, the URLs in the codebase needs to be updated by the plugin teams.

Currently, the old URL and user token is active. Infra team will update the token on 6/22. Make sure to update the URLs by then

More details: https://issues.sonatype.org/browse/OSSRH-47276

Thanks!

**Comment by weicongs-amazon** [comment]
Hi, team, pls make sure this change is done in the 1.9.0 release, otherwise, the maven publishing will fail

**Comment by joshuali925** [comment]
Thanks, updated maven endpoint in b0446c658156363d672bd3af2dbfe7212d9934cd. Closing issue.
